DISCOVERY_CLASSIFICATIONS = {
    "AVAILABLE_AND_PARSEABLE",
    "AVAILABLE_SCHEMA_UNKNOWN",
    "AVAILABLE_INVALID_CONTENT",
    "NOT_PUBLISHED_FOR_DATE",
    "PUBLIC_ARCHIVE_NOT_AVAILABLE",
    "ACCESS_DENIED",
    "RATE_LIMITED",
    "HTML_RETURNED_INSTEAD_OF_DATA",
    "CORRUPT_ARCHIVE",
    "DATE_MISMATCH",
    "UNSUPPORTED_FORMAT",
}

SPIKE_CLASSIFICATIONS = {
    "PUBLIC_NSE_BHAVCOPY_AND_CONTRACT_HISTORY_FEASIBLE",
    "PUBLIC_NSE_RECENT_UDIFF_ONLY",
    "PUBLIC_NSE_BHAVCOPY_HISTORY_WITHOUT_CONTRACT_MASTER",
    "PUBLIC_NSE_CONTRACT_MASTER_RECENT_ONLY",
    "PUBLIC_NSE_ARCHIVE_PARTIALLY_FEASIBLE",
    "PUBLIC_NSE_ACCESS_REQUIRES_MANUAL_DOWNLOAD",
    "PUBLIC_NSE_ACCESS_NOT_SUITABLE_FOR_BULK_RESEARCH",
    "PUBLIC_NSE_DATA_USAGE_REVIEW_REQUIRED",
}
