FIELD_MAPPING_STATUS = {
    "LEGACY_FO_BHAVCOPY": "INFERRED_FROM_OBSERVED_FILE",
    "UDIFF_FO_BHAVCOPY": "UNRESOLVED_OFFICIAL_WORKBOOK_REQUIRED",
    "MII_FO_CONTRACT_FILE": "UNRESOLVED_OFFICIAL_WORKBOOK_REQUIRED",
    "FO_DAILY_SETTLEMENT": "UNRESOLVED_OFFICIAL_SAMPLE_REQUIRED",
}
